import sqlite3
from contextlib import contextmanager
from pathlib import Path
from typing import Iterator

from .config import get_settings


SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    strategy_api_key_hash TEXT NOT NULL UNIQUE,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS broker_connections (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL UNIQUE REFERENCES users(id),
    broker TEXT NOT NULL DEFAULT 'PAPER',
    status TEXT NOT NULL DEFAULT 'CONNECTED',
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id),
    execution_mode TEXT NOT NULL DEFAULT 'PAPER',
    broker_order_id TEXT,
    symbol TEXT NOT NULL,
    instrument_key TEXT,
    side TEXT NOT NULL CHECK(side IN ('BUY', 'SELL')),
    quantity INTEGER NOT NULL CHECK(quantity > 0),
    filled_quantity INTEGER NOT NULL DEFAULT 0,
    order_type TEXT NOT NULL DEFAULT 'MARKET',
    product TEXT NOT NULL DEFAULT 'D',
    source TEXT NOT NULL CHECK(source IN ('MANUAL', 'STRATEGY')),
    strategy_name TEXT,
    signal_id TEXT,
    status TEXT NOT NULL,
    requested_price REAL,
    average_price REAL,
    rejection_reason TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS positions (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id),
    execution_mode TEXT NOT NULL DEFAULT 'PAPER',
    symbol TEXT NOT NULL,
    instrument_key TEXT,
    quantity INTEGER NOT NULL DEFAULT 0,
    average_price REAL NOT NULL DEFAULT 0,
    realized_pnl REAL NOT NULL DEFAULT 0,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, execution_mode, symbol)
);

CREATE TABLE IF NOT EXISTS strategies (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id),
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE', 'PAUSED')),
    signal_count INTEGER NOT NULL DEFAULT 0,
    last_signal_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, name)
);

CREATE TABLE IF NOT EXISTS market_candles (
    instrument_key TEXT NOT NULL,
    candle_date TEXT NOT NULL,
    candle_timestamp TEXT NOT NULL,
    open REAL NOT NULL,
    high REAL NOT NULL,
    low REAL NOT NULL,
    close REAL NOT NULL,
    volume INTEGER NOT NULL,
    open_interest INTEGER NOT NULL DEFAULT 0,
    provider TEXT NOT NULL,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(instrument_key, candle_date)
);

CREATE INDEX IF NOT EXISTS idx_market_candles_lookup
ON market_candles(instrument_key, candle_date);

CREATE TABLE IF NOT EXISTS saved_scanners (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id),
    name TEXT NOT NULL,
    preset_key TEXT,
    conditions_json TEXT NOT NULL DEFAULT '[]',
    rank_field TEXT NOT NULL DEFAULT 'price',
    rank_direction TEXT NOT NULL DEFAULT 'desc',
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, name)
);

CREATE TABLE IF NOT EXISTS scanner_alerts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id),
    saved_scanner_id INTEGER NOT NULL REFERENCES saved_scanners(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    minimum_matches INTEGER NOT NULL DEFAULT 1 CHECK(minimum_matches > 0),
    enabled INTEGER NOT NULL DEFAULT 1,
    last_checked_at TEXT,
    last_triggered_at TEXT,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, name)
);

CREATE TABLE IF NOT EXISTS scanner_alert_events (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    user_id INTEGER NOT NULL REFERENCES users(id),
    alert_id INTEGER NOT NULL REFERENCES scanner_alerts(id) ON DELETE CASCADE,
    match_count INTEGER NOT NULL,
    symbols_json TEXT NOT NULL DEFAULT '[]',
    data_as_of TEXT,
    is_read INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_scanner_alert_events_user
ON scanner_alert_events(user_id, created_at);
"""


POSTGRES_SCHEMA = """
CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    strategy_api_key_hash TEXT NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    name TEXT NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS broker_connections (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    broker TEXT NOT NULL DEFAULT 'PAPER',
    status TEXT NOT NULL DEFAULT 'CONNECTED',
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id)
);

CREATE TABLE IF NOT EXISTS orders (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    execution_mode TEXT NOT NULL DEFAULT 'PAPER',
    broker_order_id TEXT,
    symbol TEXT NOT NULL,
    instrument_key TEXT,
    side TEXT NOT NULL CHECK(side IN ('BUY', 'SELL')),
    quantity INTEGER NOT NULL CHECK(quantity > 0),
    filled_quantity INTEGER NOT NULL DEFAULT 0,
    order_type TEXT NOT NULL DEFAULT 'MARKET',
    product TEXT NOT NULL DEFAULT 'D',
    source TEXT NOT NULL CHECK(source IN ('MANUAL', 'STRATEGY')),
    strategy_name TEXT,
    signal_id TEXT,
    status TEXT NOT NULL,
    requested_price DOUBLE PRECISION,
    average_price DOUBLE PRECISION,
    rejection_reason TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS positions (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    execution_mode TEXT NOT NULL DEFAULT 'PAPER',
    symbol TEXT NOT NULL,
    instrument_key TEXT,
    quantity INTEGER NOT NULL DEFAULT 0,
    average_price DOUBLE PRECISION NOT NULL DEFAULT 0,
    realized_pnl DOUBLE PRECISION NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, execution_mode, symbol)
);

CREATE TABLE IF NOT EXISTS strategies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    name TEXT NOT NULL,
    description TEXT NOT NULL DEFAULT '',
    status TEXT NOT NULL DEFAULT 'ACTIVE' CHECK(status IN ('ACTIVE', 'PAUSED')),
    signal_count INTEGER NOT NULL DEFAULT 0,
    last_signal_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, name)
);

CREATE TABLE IF NOT EXISTS market_candles (
    instrument_key TEXT NOT NULL,
    candle_date TEXT NOT NULL,
    candle_timestamp TEXT NOT NULL,
    open DOUBLE PRECISION NOT NULL,
    high DOUBLE PRECISION NOT NULL,
    low DOUBLE PRECISION NOT NULL,
    close DOUBLE PRECISION NOT NULL,
    volume BIGINT NOT NULL,
    open_interest BIGINT NOT NULL DEFAULT 0,
    provider TEXT NOT NULL,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(instrument_key, candle_date)
);

CREATE INDEX IF NOT EXISTS idx_market_candles_lookup
ON market_candles(instrument_key, candle_date);

CREATE TABLE IF NOT EXISTS saved_scanners (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    name TEXT NOT NULL,
    preset_key TEXT,
    conditions_json TEXT NOT NULL DEFAULT '[]',
    rank_field TEXT NOT NULL DEFAULT 'price',
    rank_direction TEXT NOT NULL DEFAULT 'desc',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, name)
);

CREATE TABLE IF NOT EXISTS scanner_alerts (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    saved_scanner_id INTEGER NOT NULL REFERENCES saved_scanners(id) ON DELETE CASCADE,
    name TEXT NOT NULL,
    minimum_matches INTEGER NOT NULL DEFAULT 1 CHECK(minimum_matches > 0),
    enabled INTEGER NOT NULL DEFAULT 1,
    last_checked_at TIMESTAMP,
    last_triggered_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(user_id, name)
);

CREATE TABLE IF NOT EXISTS scanner_alert_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    alert_id INTEGER NOT NULL REFERENCES scanner_alerts(id) ON DELETE CASCADE,
    match_count INTEGER NOT NULL,
    symbols_json TEXT NOT NULL DEFAULT '[]',
    data_as_of TEXT,
    is_read INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_scanner_alert_events_user
ON scanner_alert_events(user_id, created_at);
"""


class PostgresCursor:
    def __init__(self, cursor, connection):
        self._cursor = cursor
        self._connection = connection

    @property
    def lastrowid(self):
        """Provide sqlite-style lastrowid for existing application code."""
        row = self._connection._connection.execute("SELECT LASTVAL() AS last_id").fetchone()
        return row["last_id"] if row else None

    def __getattr__(self, name):
        return getattr(self._cursor, name)


class PostgresConnection:
    def __init__(self, connection):
        self._connection = connection

    def __enter__(self):
        return self

    def __exit__(self, exc_type, _exc_value, _traceback):
        if exc_type:
            self.rollback()
        else:
            self.commit()
        self.close()

    def execute(self, query: str, parameters=()):
        # Application SQL uses sqlite's ? placeholders; psycopg uses %s.
        cursor = self._connection.cursor()
        cursor.execute(query.replace("?", "%s"), parameters)
        return PostgresCursor(cursor, self)

    def commit(self):
        self._connection.commit()

    def rollback(self):
        self._connection.rollback()

    def close(self):
        self._connection.close()


class Database:
    def __init__(self, path: str | None = None):
        settings = get_settings()
        self.path = path or settings.database_path
        self.url = settings.database_url.strip()

    @property
    def is_postgres(self) -> bool:
        return bool(self.url)

    def connect(self):
        if self.is_postgres:
            try:
                import psycopg
                from psycopg.rows import dict_row
            except ImportError as exc:
                raise RuntimeError("DATABASE_URL is set, but psycopg is not installed") from exc
            return PostgresConnection(psycopg.connect(self.url, row_factory=dict_row))
        if self.path != ":memory:":
            Path(self.path).parent.mkdir(parents=True, exist_ok=True)
        connection = sqlite3.connect(self.path, check_same_thread=False)
        connection.row_factory = sqlite3.Row
        connection.execute("PRAGMA foreign_keys = ON")
        connection.execute("PRAGMA journal_mode = WAL")
        return connection

    def initialize(self) -> None:
        if self.is_postgres:
            with self.transaction() as connection:
                for statement in POSTGRES_SCHEMA.split(";"):
                    if statement.strip():
                        connection.execute(statement)
                connection.execute("DROP INDEX IF EXISTS idx_orders_user_signal")
                connection.execute(
                    """CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_user_signal
                       ON orders(user_id, execution_mode, signal_id) WHERE signal_id IS NOT NULL"""
                )
                connection.execute("ALTER TABLE users ADD COLUMN IF NOT EXISTS name TEXT NOT NULL DEFAULT ''")
            return
        with self.connect() as connection:
            connection.executescript(SCHEMA)
            self._add_missing_columns(connection, "orders", {
                "execution_mode": "TEXT NOT NULL DEFAULT 'PAPER'",
                "instrument_key": "TEXT",
                "filled_quantity": "INTEGER NOT NULL DEFAULT 0",
                "product": "TEXT NOT NULL DEFAULT 'D'",
                "signal_id": "TEXT",
            })
            self._add_missing_columns(connection, "positions", {"instrument_key": "TEXT"})
            self._add_missing_columns(connection, "users", {"name": "TEXT NOT NULL DEFAULT ''"})
            self._migrate_positions_scope(connection)
            connection.execute("DROP INDEX IF EXISTS idx_orders_user_signal")
            connection.execute(
                """CREATE UNIQUE INDEX IF NOT EXISTS idx_orders_user_signal
                   ON orders(user_id, execution_mode, signal_id) WHERE signal_id IS NOT NULL"""
            )
            connection.execute(
                """UPDATE broker_connections SET broker = 'UPSTOX_LIVE', status = 'LOCKED'
                   WHERE broker = 'UPSTOX'"""
            )

    @staticmethod
    def _add_missing_columns(
        connection: sqlite3.Connection, table: str, columns: dict[str, str]
    ) -> None:
        existing = {row[1] for row in connection.execute(f"PRAGMA table_info({table})")}
        for name, definition in columns.items():
            if name not in existing:
                connection.execute(f"ALTER TABLE {table} ADD COLUMN {name} {definition}")

    @staticmethod
    def _migrate_positions_scope(connection: sqlite3.Connection) -> None:
        columns = {row[1] for row in connection.execute("PRAGMA table_info(positions)")}
        if "execution_mode" in columns:
            return
        connection.executescript(
            """
            ALTER TABLE positions RENAME TO positions_legacy;
            CREATE TABLE positions (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL REFERENCES users(id),
                execution_mode TEXT NOT NULL DEFAULT 'PAPER',
                symbol TEXT NOT NULL,
                instrument_key TEXT,
                quantity INTEGER NOT NULL DEFAULT 0,
                average_price REAL NOT NULL DEFAULT 0,
                realized_pnl REAL NOT NULL DEFAULT 0,
                updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE(user_id, execution_mode, symbol)
            );
            INSERT INTO positions
                (id, user_id, execution_mode, symbol, instrument_key, quantity,
                 average_price, realized_pnl, updated_at)
            SELECT id, user_id, 'PAPER', symbol, instrument_key, quantity,
                   average_price, realized_pnl, updated_at
            FROM positions_legacy;
            DROP TABLE positions_legacy;
            """
        )

    @contextmanager
    def transaction(self) -> Iterator[sqlite3.Connection]:
        connection = self.connect()
        try:
            connection.execute("BEGIN" if self.is_postgres else "BEGIN IMMEDIATE")
            yield connection
            connection.commit()
        except Exception:
            connection.rollback()
            raise
        finally:
            connection.close()


db = Database()
